                <section class="main-section grid_8">
                    <nav class="collapsed">
                        <a class="chevron" href="#">&raquo;</a>
                        <ul>
                            <li class="current"><a href="<?=$this->baseUrl('account')?>" class="navicon-sliders">Settings</a></li>
                            <li><a href="<?=$this->baseUrl('account/themes')?>" class="navicon-palette">Themes</a></li>
                        </ul>
                    </nav>

                    <div class="main-content">
                        <header>
                            <ul class="action-buttons clearfix">
                                <li><a href="<?=$this->baseUrl('documentation/index.html')?>" class="button help" rel="#overlay" data-icon-primary="ui-icon-help" data-icon-only="true">Help</a></li>
                            </ul>
                            <h2>
                                Account Settings
                            </h2>
                        </header>
                        <section class="container_6 clearfix">
                            <div class="grid_6">
                                <div class="ui-widget message">
                                    <div class="ui-state-highlight ui-corner-all">
                                        <p>
                                            <span class="ui-icon ui-icon-info"></span>
                                            <strong>SPECIAL OFFER:</strong>
                                            Upgrade today and get 10% off your first month.
                                            Click "Upgrade" below and enter the coupon code.
                                        <p>
                                    </div>
                                </div>
                                
                                <div class="portlet">
                                    <header>
                                        <h2>Other plans to choose from</h2>
                                    </header>
                                    <section class="no-padding">
                                        <table class="simple full ui-corner-bottom">
                                            <thead>
                                                <tr>
                                                    <th class="ui-state-default">Plan</th>
                                                    <th class="ui-state-default">Users</th>
                                                    <th class="ui-state-default">Storage</th>
                                                    <th class="ui-state-default">Contacts</th>
                                                    <th class="ui-state-default" style="width: 80px;">&nbsp;</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><strong>Super <span>$129/month</span></strong></td>
                                                    <td class="ac">Unlimited</td>
                                                    <td class="ac">100 GB</td>
                                                    <td class="ac">50000</td>
                                                    <td class="ac"><a href="#" class="button">Upgrade</a></td>
                                                </tr>
                                                <tr>
                                                    <td><strong>Premium <span>$99/month</span></strong></td>
                                                    <td class="ac">60</td>
                                                    <td class="ac">50 GB</td>
                                                    <td class="ac">20000</td>
                                                    <td class="ac"><a href="#" class="button">Upgrade</a></td>
                                                </tr>
                                                <tr>
                                                    <td><strong>Plus <span>$59/month</span></strong></td>
                                                    <td class="ac">30</td>
                                                    <td class="ac">25 GB</td>
                                                    <td class="ac">5000</td>
                                                    <td class="ac"><a href="#" class="button">Upgrade</a></td>
                                                </tr>
                                                <tr>
                                                    <td><strong>Basic <span>$29/month</span></strong></td>
                                                    <td class="ac">15</td>
                                                    <td class="ac">10 GB</td>
                                                    <td class="ac">2000</td>
                                                    <td class="ac"><a href="#" class="button">Upgrade</a></td>
                                                </tr>
                                                <tr class="highlight ui-corner-bottom">
                                                    <td class="ui-corner-bl"><strong>Free</strong></td>
                                                    <td class="ac">2</td>
                                                    <td class="ac">&mdash;</td>
                                                    <td class="ac">100</td>
                                                    <td class="ac ui-corner-br"><strong>Your Plan</strong></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </section>
                                </div>
                            </div>
                        </section>
                    </div>

                </section>