                <section class="main-section grid_8">
                    <nav class="collapsed">
                        <a class="chevron" href="#">&raquo;</a>
                        <ul>
                            <li><a href="<?=$this->baseUrl('account')?>" class="navicon-sliders">Settings</a></li>
                            <li class="current"><a href="<?=$this->baseUrl('account/themes')?>" class="navicon-palette">Themes</a></li>
                        </ul>
                    </nav>

                    <div class="main-content">
                        <header>
                            <ul class="action-buttons clearfix">
                                <li><a href="<?=$this->baseUrl('documentation/index.html')?>" class="button help" rel="#overlay" data-icon-primary="ui-icon-help" data-icon-only="true">Help</a></li>
                            </ul>
                            <h2>
                                Themes
                            </h2>
                        </header>
                        <section class="container_6 clearfix">
                            <div class="grid_6">
                                <h3 class="ui-widget-header ui-corner-all">Current Theme: <?=$this->currentthemeinfo["Theme Name"]?> by <?=$this->currentthemeinfo["Author"]?></h3>
                                <div class="grid_2 alpha">
                                    <img src="<?=$this->baseUrl('css/ui/' . THEME . '/screenshot.png')?>" style="width:100%" />
                                </div>
                                <div class="grid_4 omega">
                                    <fieldset class="ui-corner-all">
                                        <legend>Color Scheme</legend>
                                        <section>
                                            <ul id="theme-colorschemes" class="clearfix">
                                            <?php foreach($this->colors as $color):?>
                                                <li><a href="#" title="<?=$color["Color Scheme Name"]?>" style="background-color: <?=$color["Color Scheme"]?>;" rel="<?=$this->baseUrl($color["url"])?>" onclick="changeUicolor($(this).attr('rel')); return false;"></a></li>
                                            <?php endforeach;?>
                                            </ul>
                                        </section>
                                    </fieldset>
                                    <fieldset class="ui-corner-all leading">
                                        <legend>Background</legend>
                                        <section>
                                            <ul id="theme-backgrounds" class="clearfix">
                                            <?php foreach($this->backgrounds as $background):?>
                                                <li><a href="#" style="background: transparent url(<?=$this->baseUrl('images/backgrounds/'.$background)?>) repeat 0 0;" onclick="changeBackground('bg<?=str_replace('.','-',$background)?>'); return false;"></a></li>
                                            <?php endforeach;?>
                                            </ul>
                                        </section>
                                    </fieldset>
                                </div>
                            </div>
                                
                            <div class="grid_6 leading">
                                <h3 class="ui-widget-header ui-corner-all">Available Themes</h3>
                            </div>
                            
                            <div class="clear"></div>
                            <?php foreach($this->themes as $theme):?>
                            <div class="grid_2">
                                <img src="<?=$this->baseUrl($theme["url"] . '/screenshot.png')?>" style="width:100%" />
                                <h4><?=$theme["Theme Name"]?> by <?=$theme["Author"]?></h4>
                                <a href="<?=$this->baseUrl("account/themes?activatetheme=" . $theme["directory"])?>">Activate</a>
                            </div>
                            <?php endforeach;?>
                            
                            <div class="clear"></div>
                            
                            <div class="grid_6 leading">
                                <div class="ui-widget message">
                                    <div class="ui-state-highlight ui-corner-all">
                                        <p>
                                            <span class="ui-icon ui-icon-info"></span>
                                            To create a new theme, just copy the existing theme under css/ui folder and give it a new name, and modify the css as you wish.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>

                </section>