<section class="main-section grid_8">
    <section class="main-content grid_8 alpha omega">
        <header>
            <h2>Ooops! Something happened...</h2>
        </header>
        <section>
            <h1>An error occurred</h1>
            <h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>

            <h3>Exception information:</h3>
            <p>
                <b>Message:</b> <?php echo $this->exception->getMessage() ?>
            </p>

            <h3>Stack trace:</h3>
            <pre><?php echo $this->exception->getTraceAsString() ?>
            </pre>

            <h3>Request Parameters:</h3>
            <pre><?php echo var_export($this->request->getParams(), true) ?>
            </pre>
<?php endif ?>
        </section>
    </section>
</section>