                <section class="main-section grid_8">
                    <nav class="collapsed">
                        <a class="chevron" href="#">&raquo;</a>
                        <ul>
                            <li><a href="<?=$this->baseUrl('demo/wysiwyg')?>" class="navicon-folder-open">WYSIWYG</a></li>
                            <li><a href="<?=$this->baseUrl('demo/forms')?>" class="navicon-id-card">Forms</a></li>
                            <li><a href="<?=$this->baseUrl('demo/widgets')?>" class="navicon-window">Widgets</a></li>
                            <li><a href="<?=$this->baseUrl('demo/tables')?>" class="navicon-table">Tables</a></li>
                            <li><a href="<?=$this->baseUrl('demo/styles')?>" class="navicon-palette">Styles</a></li>
                            <li><a href="<?=$this->baseUrl('demo/navicons')?>" class="navicon-photos">Nav Icons</a></li>
                            <li class="current"><a href="<?=$this->baseUrl('demo/grid')?>" class="navicon-grid">Grid System</a></li>
                        </ul>
                    </nav>

                    <div class="main-content">
                        <header>
                            <h2>Grid System</h2>
                        </header>
                        <section class="container_6 clearfix">
                            <div class="grid_6">
                                <div class="portlet">
                                    <header>
                                        <h2>grid_6</h2>
                                    </header>
                                    <section>
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                                    </section>
                                </div>
                            </div>
                            
                            <div class="grid_6 leading">
                                <div class="grid_1 alpha">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_1</h2>
                                        </header>
                                    <section>
                                        Lorem Ipsum is simply dummy text of the printing and typesetting...
                                    </section>
                                    </div>
                                </div>
                                <div class="grid_5 omega">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_5</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                                        </section>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="grid_6 leading">
                                <div class="grid_2 alpha">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_2</h2>
                                        </header>
                                    <section>
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                    </section>
                                    </div>
                                </div>
                                <div class="grid_4 omega">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_4</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                                        </section>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="grid_6 leading">
                                <div class="grid_3 alpha">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_3</h2>
                                        </header>
                                    <section>
                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                                    </section>
                                    </div>
                                </div>
                                <div class="grid_3 omega">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_3</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                                        </section>
                                    </div>
                                </div>
                            </div>

                            <div class="grid_6 leading">
                                <div class="grid_2 alpha">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_2</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                        </section>
                                    </div>
                                </div>
                                <div class="grid_2">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_2</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                        </section>
                                    </div>
                                </div>
                                <div class="grid_2 omega">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_2</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                                        </section>
                                    </div>
                                </div>
                            </div>

                            <div class="grid_6 leading">
                                <div class="grid_1 alpha">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_1</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                        </section>
                                    </div>
                                </div>
                                <div class="grid_1">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_1</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                        </section>
                                    </div>
                                </div>
                                <div class="grid_1">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_1</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                        </section>
                                    </div>
                                </div>
                                <div class="grid_1">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_1</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                        </section>
                                    </div>
                                </div>
                                <div class="grid_1">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_1</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                        </section>
                                    </div>
                                </div>
                                <div class="grid_1 omega">
                                    <div class="portlet">
                                        <header>
                                            <h2>grid_1</h2>
                                        </header>
                                        <section>
                                            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                        </section>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                    <!-- End Styles Section -->

                </section>

