                <section class="main-section grid_8">
                    <nav class="collapsed">
                        <a class="chevron" href="#">&raquo;</a>
                        <ul>
                            <li><a href="<?=$this->baseUrl('demo/wysiwyg')?>" class="navicon-folder-open">WYSIWYG</a></li>
                            <li><a href="<?=$this->baseUrl('demo/forms')?>" class="navicon-id-card">Forms</a></li>
                            <li><a href="<?=$this->baseUrl('demo/widgets')?>" class="navicon-window">Widgets</a></li>
                            <li><a href="<?=$this->baseUrl('demo/tables')?>" class="navicon-table">Tables</a></li>
                            <li><a href="<?=$this->baseUrl('demo/styles')?>" class="navicon-palette">Styles</a></li>
                            <li class="current"><a href="<?=$this->baseUrl('demo/navicons')?>" class="navicon-photos">Nav Icons</a></li>
                            <li><a href="<?=$this->baseUrl('demo/grid')?>" class="navicon-grid">Grid System</a></li>
                        </ul>
                    </nav>

                    <!-- Styles Section -->
                    <div class="main-content">
                        <header>
                            <h2>Nav Icons</h2>
                        </header>
                        <section class="container_6 clearfix">
                            <ul class="display-inline">
                                <li title=".navicon-refresh"><img src="<?=$this->baseUrl('images/navicons/01.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-redo"><img src="<?=$this->baseUrl('images/navicons/02.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-loopback"><img src="<?=$this->baseUrl('images/navicons/03.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-squiggle"><img src="<?=$this->baseUrl('images/navicons/04.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-shuffle"><img src="<?=$this->baseUrl('images/navicons/05.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-magnify"><img src="<?=$this->baseUrl('images/navicons/06.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-map-marker"><img src="<?=$this->baseUrl('images/navicons/07.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-chat-1"><img src="<?=$this->baseUrl('images/navicons/08.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-chat-2"><img src="<?=$this->baseUrl('images/navicons/09.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-medical"><img src="<?=$this->baseUrl('images/navicons/10.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-clock"><img src="<?=$this->baseUrl('images/navicons/11.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-eye"><img src="<?=$this->baseUrl('images/navicons/12.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-target"><img src="<?=$this->baseUrl('images/navicons/13.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-tag"><img src="<?=$this->baseUrl('images/navicons/14.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-tags"><img src="<?=$this->baseUrl('images/navicons/15.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-line-chart"><img src="<?=$this->baseUrl('images/navicons/16.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-bar-chart"><img src="<?=$this->baseUrl('images/navicons/17.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-mail"><img src="<?=$this->baseUrl('images/navicons/18.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-gear-1"><img src="<?=$this->baseUrl('images/navicons/19.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-gear-2"><img src="<?=$this->baseUrl('images/navicons/20.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-gift"><img src="<?=$this->baseUrl('images/navicons/21.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-weather"><img src="<?=$this->baseUrl('images/navicons/22.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-star"><img src="<?=$this->baseUrl('images/navicons/23.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-heart"><img src="<?=$this->baseUrl('images/navicons/24.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-key"><img src="<?=$this->baseUrl('images/navicons/25.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-window"><img src="<?=$this->baseUrl('images/navicons/26.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-grid"><img src="<?=$this->baseUrl('images/navicons/27.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-layout"><img src="<?=$this->baseUrl('images/navicons/28.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-table"><img src="<?=$this->baseUrl('images/navicons/29.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-folder-open"><img src="<?=$this->baseUrl('images/navicons/30.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-ipod"><img src="<?=$this->baseUrl('images/navicons/31.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-iphone"><img src="<?=$this->baseUrl('images/navicons/32.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-cabinet"><img src="<?=$this->baseUrl('images/navicons/33.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-coffee"><img src="<?=$this->baseUrl('images/navicons/34.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-shopping"><img src="<?=$this->baseUrl('images/navicons/35.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-toolbox"><img src="<?=$this->baseUrl('images/navicons/36.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-suitcase"><img src="<?=$this->baseUrl('images/navicons/37.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-airplane"><img src="<?=$this->baseUrl('images/navicons/38.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-outbox"><img src="<?=$this->baseUrl('images/navicons/39.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-inbox"><img src="<?=$this->baseUrl('images/navicons/40.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-picture-frame"><img src="<?=$this->baseUrl('images/navicons/41.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-photos"><img src="<?=$this->baseUrl('images/navicons/42.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-film-roll"><img src="<?=$this->baseUrl('images/navicons/43.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-shoebox"><img src="<?=$this->baseUrl('images/navicons/44.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-movie-1"><img src="<?=$this->baseUrl('images/navicons/45.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-movie-2"><img src="<?=$this->baseUrl('images/navicons/46.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-fuel"><img src="<?=$this->baseUrl('images/navicons/47.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-battery-1"><img src="<?=$this->baseUrl('images/navicons/48.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-battery-2"><img src="<?=$this->baseUrl('images/navicons/49.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-battery-3"><img src="<?=$this->baseUrl('images/navicons/50.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-outlet"><img src="<?=$this->baseUrl('images/navicons/51.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-pine-tree"><img src="<?=$this->baseUrl('images/navicons/52.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-house"><img src="<?=$this->baseUrl('images/navicons/53.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-lock"><img src="<?=$this->baseUrl('images/navicons/54.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-network"><img src="<?=$this->baseUrl('images/navicons/55.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-cloud-upload"><img src="<?=$this->baseUrl('images/navicons/56.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-download"><img src="<?=$this->baseUrl('images/navicons/57.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-bookmark"><img src="<?=$this->baseUrl('images/navicons/58.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-flag"><img src="<?=$this->baseUrl('images/navicons/59.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-signpost"><img src="<?=$this->baseUrl('images/navicons/60.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-brightness"><img src="<?=$this->baseUrl('images/navicons/61.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-contrast"><img src="<?=$this->baseUrl('images/navicons/62.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-walk"><img src="<?=$this->baseUrl('images/navicons/63.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-export"><img src="<?=$this->baseUrl('images/navicons/64.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-import"><img src="<?=$this->baseUrl('images/navicons/65.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-microphone"><img src="<?=$this->baseUrl('images/navicons/66.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-vault"><img src="<?=$this->baseUrl('images/navicons/67.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-paperclip"><img src="<?=$this->baseUrl('images/navicons/68.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-display"><img src="<?=$this->baseUrl('images/navicons/69.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-tv"><img src="<?=$this->baseUrl('images/navicons/70.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-compass"><img src="<?=$this->baseUrl('images/navicons/71.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-pin"><img src="<?=$this->baseUrl('images/navicons/72.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-trash-bin"><img src="<?=$this->baseUrl('images/navicons/73.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-location"><img src="<?=$this->baseUrl('images/navicons/74.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-phone-1"><img src="<?=$this->baseUrl('images/navicons/75.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-phone-2"><img src="<?=$this->baseUrl('images/navicons/76.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-ekg"><img src="<?=$this->baseUrl('images/navicons/77.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-stopwatch"><img src="<?=$this->baseUrl('images/navicons/78.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-medical-bag"><img src="<?=$this->baseUrl('images/navicons/79.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-shopping-cart"><img src="<?=$this->baseUrl('images/navicons/80.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-dashboard"><img src="<?=$this->baseUrl('images/navicons/81.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-dog-paw"><img src="<?=$this->baseUrl('images/navicons/82.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-calendar"><img src="<?=$this->baseUrl('images/navicons/83.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-lightbulb"><img src="<?=$this->baseUrl('images/navicons/84.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-trophy"><img src="<?=$this->baseUrl('images/navicons/85.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-camera"><img src="<?=$this->baseUrl('images/navicons/86.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-wine-glass"><img src="<?=$this->baseUrl('images/navicons/87.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-beer-glass"><img src="<?=$this->baseUrl('images/navicons/88.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-dumbbells"><img src="<?=$this->baseUrl('images/navicons/89.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-lifebuoy"><img src="<?=$this->baseUrl('images/navicons/90.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-certificate"><img src="<?=$this->baseUrl('images/navicons/91.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-checkmark"><img src="<?=$this->baseUrl('images/navicons/92.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-checkbox-checked"><img src="<?=$this->baseUrl('images/navicons/93.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-printer"><img src="<?=$this->baseUrl('images/navicons/94.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-equalizer"><img src="<?=$this->baseUrl('images/navicons/95.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-book"><img src="<?=$this->baseUrl('images/navicons/96.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-puzzle-piece"><img src="<?=$this->baseUrl('images/navicons/97.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-palette"><img src="<?=$this->baseUrl('images/navicons/98.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-umbrella"><img src="<?=$this->baseUrl('images/navicons/99.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-link"><img src="<?=$this->baseUrl('images/navicons/100.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-push-pin"><img src="<?=$this->baseUrl('images/navicons/101.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-document"><img src="<?=$this->baseUrl('images/navicons/102.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-document-new"><img src="<?=$this->baseUrl('images/navicons/103.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-index-cards"><img src="<?=$this->baseUrl('images/navicons/104.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-piano"><img src="<?=$this->baseUrl('images/navicons/105.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-sliders"><img src="<?=$this->baseUrl('images/navicons/106.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-widescreen"><img src="<?=$this->baseUrl('images/navicons/107.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-badge"><img src="<?=$this->baseUrl('images/navicons/108.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-database"><img src="<?=$this->baseUrl('images/navicons/109.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-bug"><img src="<?=$this->baseUrl('images/navicons/110.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-user"><img src="<?=$this->baseUrl('images/navicons/111.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-group"><img src="<?=$this->baseUrl('images/navicons/112.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-navigation"><img src="<?=$this->baseUrl('images/navicons/113.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-podcast"><img src="<?=$this->baseUrl('images/navicons/114.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-rss-1"><img src="<?=$this->baseUrl('images/navicons/115.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-rss-2"><img src="<?=$this->baseUrl('images/navicons/116.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-todo"><img src="<?=$this->baseUrl('images/navicons/117.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-hanger"><img src="<?=$this->baseUrl('images/navicons/118.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-shield"><img src="<?=$this->baseUrl('images/navicons/119.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-headphone"><img src="<?=$this->baseUrl('images/navicons/120.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-landscape"><img src="<?=$this->baseUrl('images/navicons/121.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-stats"><img src="<?=$this->baseUrl('images/navicons/122.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-id-card"><img src="<?=$this->baseUrl('images/navicons/123.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-bullhorn"><img src="<?=$this->baseUrl('images/navicons/124.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-volume-high"><img src="<?=$this->baseUrl('images/navicons/125.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-volume-low"><img src="<?=$this->baseUrl('images/navicons/126.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-volume-mute"><img src="<?=$this->baseUrl('images/navicons/127.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-money"><img src="<?=$this->baseUrl('images/navicons/128.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-power"><img src="<?=$this->baseUrl('images/navicons/129.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-connected"><img src="<?=$this->baseUrl('images/navicons/130.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-tower"><img src="<?=$this->baseUrl('images/navicons/131.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-dollar"><img src="<?=$this->baseUrl('images/navicons/132.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-pound"><img src="<?=$this->baseUrl('images/navicons/133.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-x"><img src="<?=$this->baseUrl('images/navicons/134.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-minus"><img src="<?=$this->baseUrl('images/navicons/135.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-box"><img src="<?=$this->baseUrl('images/navicons/136.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-presentation"><img src="<?=$this->baseUrl('images/navicons/137.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-scales"><img src="<?=$this->baseUrl('images/navicons/138.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-menu"><img src="<?=$this->baseUrl('images/navicons/139.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-pulldown"><img src="<?=$this->baseUrl('images/navicons/140.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-lamp"><img src="<?=$this->baseUrl('images/navicons/141.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-wine-bottle"><img src="<?=$this->baseUrl('images/navicons/142.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-liquor-bottle"><img src="<?=$this->baseUrl('images/navicons/143.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-martini"><img src="<?=$this->baseUrl('images/navicons/144.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-persondot"><img src="<?=$this->baseUrl('images/navicons/145.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-gavel"><img src="<?=$this->baseUrl('images/navicons/146.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-controller"><img src="<?=$this->baseUrl('images/navicons/147.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-wrench-1"><img src="<?=$this->baseUrl('images/navicons/148.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-wrench-2"><img src="<?=$this->baseUrl('images/navicons/149.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-voicemail"><img src="<?=$this->baseUrl('images/navicons/150.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-calculator"><img src="<?=$this->baseUrl('images/navicons/151.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-receipt"><img src="<?=$this->baseUrl('images/navicons/152.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-newspaper"><img src="<?=$this->baseUrl('images/navicons/153.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-upload-photo-2"><img src="<?=$this->baseUrl('images/navicons/154.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-upload-photo-2"><img src="<?=$this->baseUrl('images/navicons/155.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-imac"><img src="<?=$this->baseUrl('images/navicons/156.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-macbook"><img src="<?=$this->baseUrl('images/navicons/157.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-ipad"><img src="<?=$this->baseUrl('images/navicons/158.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-building"><img src="<?=$this->baseUrl('images/navicons/159.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-notepad"><img src="<?=$this->baseUrl('images/navicons/160.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-sticky-note"><img src="<?=$this->baseUrl('images/navicons/161.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-hammer"><img src="<?=$this->baseUrl('images/navicons/162.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-warning"><img src="<?=$this->baseUrl('images/navicons/163.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-truck"><img src="<?=$this->baseUrl('images/navicons/164.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-pencil"><img src="<?=$this->baseUrl('images/navicons/165.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-paint-roller"><img src="<?=$this->baseUrl('images/navicons/166.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-bank"><img src="<?=$this->baseUrl('images/navicons/167.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-collection"><img src="<?=$this->baseUrl('images/navicons/168.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-credit-card"><img src="<?=$this->baseUrl('images/navicons/169.png')?>" width="48" height="48" /></li>
                                <li title=".navicon-barcode"><img src="<?=$this->baseUrl('images/navicons/170.png')?>" width="48" height="48" /></li>
                            </ul>
                        </section>
                    </div>
                </section>

