                <section class="main-section grid_8">
                    <nav class="collapsed">
                        <a class="chevron" href="#">&raquo;</a>
                        <ul>
                            <li><a href="<?=$this->baseUrl('dashboard')?>" class="navicon-house">Overview</a></li>
                            <li class="current"><a href="<?=$this->baseUrl('dashboard/activity')?>" class="navicon-ekg">Activity</a></li>
                            <li><a href="<?=$this->baseUrl('dashboard/files')?>" class="navicon-cabinet">File Manager</a></li>
                            <li><a href="<?=$this->baseUrl('dashboard/calendar')?>" class="navicon-calendar">Calendar</a></li>
                            <li><a href="<?=$this->baseUrl('dashboard/contacts')?>#" class="navicon-id-card">Contacts</a></li>
                        </ul>
                    </nav>

                    <div class="main-content">
                        <header>
                            <ul class="action-buttons clearfix">
                                <li><a href="<?=$this->baseUrl('account')?>" class="button" data-icon-primary="ui-icon-wrench" data-icon-only="true">Options</a></li>
                                <li><a href="documentation/index.html" class="button help" rel="#overlay" data-icon-primary="ui-icon-help" data-icon-only="true">Help</a></li>
                            </ul>
                            <h2>
                                Activity
                            </h2>
                        </header>
                        <section class="container_6 clearfix">
                            <div class="grid_6">
                                <table class="display">
                                    <thead>
                                        <tr>
                                            <th class="ui-state-default">Date</th>
                                            <th class="ui-state-default">Description</th>
                                            <th class="ui-state-default">Username</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Completed </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Running Usage Stats Update </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Closing Inactive Support Tickets </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Sending Domain Renewal Notices </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Sending Invoice Reminders </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Credit Card Payments Processed (0 Captured, 0 Failed) </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Credit Card Processing </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Adding Late Fees </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Generating Invoices </td><td>System</td></tr>
                                        <tr><td>05/03/2011 00:00</td><td>Cron Job: Updating Currency Exchange Rates </td><td>System</td></tr>
                                    </tbody>
                                </table>
                            </div>
                        </section>
                    </div>

                </section>