<script type="text/javascript"> 
	$(document).ready(function(){
        
        var f = $('#finder').elfinder({
            url : '<?=$this->baseUrl('dashboard/files')?>',
            lang : 'en',
            closeOnEditorCallback : false
            // docked : true,
            // dialog : {
            // 	title : 'File manager',
            // 	height : 500
            // }
        }).find('.el-finder-toolbar').addClass('ui-corner-top');
	});
</script> 

                <section class="main-section grid_8">
                    <nav class="collapsed">
                        <a class="chevron" href="#">&raquo;</a>
                        <ul>
                            <li><a href="<?=$this->baseUrl('dashboard')?>" class="navicon-house">Overview</a></li>
                            <li><a href="<?=$this->baseUrl('dashboard/activity')?>" class="navicon-ekg">Activity</a></li>
                            <li class="current"><a href="<?=$this->baseUrl('dashboard/files')?>" class="navicon-cabinet">File Manager</a></li>
                            <li><a href="<?=$this->baseUrl('dashboard/calendar')?>" class="navicon-calendar">Calendar</a></li>
                            <li><a href="<?=$this->baseUrl('dashboard/contacts')?>#" class="navicon-id-card">Contacts</a></li>
                        </ul>
                    </nav>

                    <div class="main-content">
                        <header>
                            <ul class="action-buttons clearfix">
                                <li><a href="<?=$this->baseUrl('account')?>" class="button" data-icon-primary="ui-icon-wrench" data-icon-only="true">Options</a></li>
                                <li><a href="<?=$this->baseUrl('documentation/index.html')?>" class="button help" rel="#overlay" data-icon-primary="ui-icon-help" data-icon-only="true">Help</a></li>
                            </ul>
                            <h2>
                                File Manager
                            </h2>
                        </header>
                        <section class="container_6 clearfix">
                            <div class="grid_6">
                                <div id="finder"></div>
                            </div>
                        </section>
                    </div>

                </section>