<?php
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

$this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:extralight,light,regular,bold')
                 ->appendStylesheet('http://fonts.googleapis.com/css?family=PT+Serif+Caption')
                 ->appendStylesheet($this->baseUrl('css/reset.css'))
                 ->appendStylesheet($this->baseUrl('css/grid.css'))
                 ->appendStylesheet($this->baseUrl('css/style.css'))
                 ->appendStylesheet($this->baseUrl('css/ui/'.THEME.'/ui.css'))
                 ->appendStylesheet($this->baseUrl('css/ui/'.THEME.'/portlet.css'))
                 ->appendStylesheet($this->baseUrl('css/ui/'.THEME.'/jquery.ui.uniform.css'))
                 ->appendStylesheet($this->baseUrl('css/ui/'.THEME.'/colors/jquery.ui.colors.default.css'), array("screen"), NULL, array("class"=>"uicolor"))
                 ->appendStylesheet($this->baseUrl('css/forms.css'))
                 ->appendStylesheet($this->baseUrl('css/ie.css'), "screen", "lt IE 8");

$this->headScript()->appendFile($this->baseUrl('js/html5.js'), "text/javascript", array("conditional" => "lt IE 9"))
                   ->appendFile($this->baseUrl('js/jquery.min.js'))
                   ->appendFile($this->baseUrl('js/jquery.cookie.js'))
                   ->appendFile($this->baseUrl('js/jquery.tools.min.js'))
                   ->appendFile($this->baseUrl('js/jquery.ui.min.js'))
                   ->appendFile($this->baseUrl('js/jquery.uniform.min.js'))
                   ->appendFile($this->baseUrl('js/global.js'))
                   ->appendFile($this->baseUrl('js/selectivizr.js'), "text/javascript", array("conditional" => "lt IE 9"))
                   ->appendFile($this->baseUrl('js/ie.js'), "text/javascript", array("conditional" => "lt IE 9"));
?>
<!DOCTYPE html>
<html lang="en">
<head>
<?php
echo $this->headMeta();
echo $this->headTitle();
echo $this->headLink();
echo $this->headScript();
?>

<script> 
$(document).ready(function(){
    $.tools.validator.fn("#username", function(input, value) {
        return value!='Username' ? true : {     
            en: "Please complete this mandatory field"
        };
    });
    
    $.tools.validator.fn("#password", function(input, value) {
        return value!='Password' ? true : {     
            en: "Please complete this mandatory field"
        };
    });

    var form = $("#form").validator({ 
    	position: 'bottom left', 
    	offset: [5, 0],
    	messageClass:'form-error',
    	message: '<div><em/></div>' // em element is the arrow
    }).attr('novalidate', 'novalidate');
});
</script> 

<!-- LOADING SCRIPT -->
<script>
$(window).load(function(){
    $("#loading").fadeOut(function(){
        $(this).remove();
        $('body').css('overflow', 'auto');
    });
});
</script>

<style type = "text/css">
    body{overflow: hidden;}
    #container {position: absolute; top:50%; left:50%;}
    #content {width:800px; text-align:center; margin-left: -400px; height:50px; margin-top:-25px; line-height: 50px;}
    #content {font-family: "Helvetica", "Arial", sans-serif; font-size: 18px; color: black; text-shadow: 0px 1px 0px white; }
    #loadinggraphic {margin-right: 0.2em; margin-bottom:-2px;}
    #loading {background-color: #eeeeee; overflow:hidden; width:100%; height:100%; position: absolute; top: 0; left: 0; z-index: 9999;}
</style> 
<!-- LOADING SCRIPT END -->

</head>
<body class="login">

    <div id="loading"> 
        <script type = "text/javascript"> 
            document.write("<div id='container'><p id='content'>" +
                           "<img id='loadinggraphic' width='16' height='16' src='<?=$this->baseUrl('images/ajax-loader-eeeeee.gif')?>' /> " +
                           "Loading...</p></div>");
        </script> 
    </div> 

    <div class="login-box main-content">
      <header>
          <ul class="action-buttons clearfix">
              <li><a href="#" class="button">Register</a></li>
              <li><a href="#" class="button" data-icon-primary="ui-icon-help">Forgot Password</a></li>
          </ul>
          <h2>vPanel Login</h2>
      </header>
    	<section>
    		<div class="ui-widget message notice">
                <div class="ui-state-highlight ui-corner-all">
                    <p>
                    <span class="ui-icon ui-icon-info"></span>
                        Enter any letter and press Login
                    </p>
                </div>
            </div>
    		<form id="form" action="<?=$this->baseUrl("login")?>" method="post" class="clearfix">
                <p>
                    <input type="text" id="username"  class="large" value="" name="username" required="required" placeholder="Username" />
                    <input type="password" id="password" class="large" value="" name="password" required="required" placeholder="Password" />
                    <button class="large button-gray ui-corner-all fr" type="submit">Login</button>
                </p>
                <p class="clearfix">
                    <span class="fl">
                        <input type="checkbox" id="remember" class="" value="1" name="remember"/>
                        <label class="choice" for="remember">Keep me logged-in for two weeks</label>
                    </span>
                </p>
            </form>
    	</section>
    </div>
</body>
</html>